server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mkdata
    username: sa
    password:
  h2: 
    console:
      enabled: true
      path: /h2
  jpa: 
      hibernate:
        ddl-auto: create